import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { DATA_SPACES, E2E_SYNTHETIC_DATA_SPACE_ID } from '$lib/state/triplit/data-space';
import { parseCalibrationManifest } from '../belgrade/calibration-manifest';
import { prepareScenarioImport } from '../belgrade/scenario-import';

/** Generated by `scripts/generate-synthetic-manifest.mjs`; the anchor there is 2026-09-06. */
const fixtureUrl = new URL('../../../../e2e/fixtures/time-dense.synthetic.json', import.meta.url);
const ANCHOR = Date.UTC(2026, 8, 6);
const DAY_MS = 86_400_000;

const manifest = parseCalibrationManifest(JSON.parse(readFileSync(fixtureUrl, 'utf8')));
const scopes = manifest.candidates.filter((candidate) => candidate.role === 'scope');
const traces = manifest.candidates.filter((candidate) => candidate.role === 'trace');
const periods = manifest.candidates.filter((candidate) => candidate.role === 'period');
const links = manifest.candidates.filter((candidate) => candidate.role === 'intersection');
const absolute = traces.flatMap((trace) =>
	trace.proposed.aboutTime?.basis === 'absolute'
		? [{ kind: trace.proposed.aboutKind, ...trace.proposed.aboutTime }]
		: []
);
const spanDays = (start: string, end: string | null): number =>
	end ? (Date.parse(end) - Date.parse(start)) / DAY_MS : 0;
const groupSizes = (keys: string[]): number[] =>
	[...Map.groupBy(keys, (key) => key).values()].map((group) => group.length);

describe('time-dense synthetic fixture', () => {
	it('is a dense two-year corpus with a three-level Scope tree', () => {
		const parents = new Map(
			links
				.filter((link) => link.proposed.kind === 'child_of')
				.map((link) => [link.proposed.fromId, link.proposed.toId])
		);
		const depth = (id: string): number => (parents.has(id) ? 1 + depth(parents.get(id)!) : 1);
		expect(scopes.length).toBeGreaterThanOrEqual(12);
		expect(Math.max(...scopes.map((scope) => depth(scope.candidateId)))).toBe(3);

		expect(traces.length).toBeGreaterThanOrEqual(400);
		const offAxis = traces.filter((trace) => trace.proposed.aboutTime?.basis === 'unknown');
		expect(offAxis.length).toBeGreaterThanOrEqual(5);
		expect(offAxis.length + absolute.length).toBe(traces.length);

		const starts = absolute.map((time) => Date.parse(time.start));
		expect(Math.min(...starts)).toBeGreaterThanOrEqual(ANCHOR - 2 * 366 * DAY_MS);
		expect(Math.max(...starts)).toBeLessThanOrEqual(ANCHOR);

		const intervals = absolute.filter((time) => time.kind === 'interval');
		expect(intervals.length).toBeGreaterThanOrEqual(80);
		expect(
			intervals.filter((time) => spanDays(time.start, time.end) >= 30).length
		).toBeGreaterThanOrEqual(10);

		const sameMinute = groupSizes(
			absolute.filter((time) => time.precision === 'minute').map((time) => time.start)
		);
		expect(sameMinute.filter((size) => size >= 2).length).toBeGreaterThanOrEqual(10);
		const perDay = groupSizes(absolute.map((time) => time.start.slice(0, 10)));
		expect(perDay.filter((size) => size >= 8).length).toBeGreaterThanOrEqual(5);
		expect(periods.length).toBeGreaterThanOrEqual(3);
		// Every trace belongs to exactly one Scope.
		expect(links.filter((link) => link.proposed.kind === 'belongs_to').length).toBe(traces.length);
	});

	it('prepares a scenario import into e2e-synthetic without skips', () => {
		const batch = prepareScenarioImport({
			manifest,
			target: DATA_SPACES[E2E_SYNTHETIC_DATA_SPACE_ID],
			capturedAt: '2026-09-06T12:00:00.000Z'
		});

		expect(batch.targetDataSpaceId).toBe(E2E_SYNTHETIC_DATA_SPACE_ID);
		expect(batch.skipped).toEqual([]);
		expect(batch.entries.length).toBe(manifest.candidates.length);
		console.info(
			`time-dense fixture: ${scopes.length} scope, ${traces.length} trace ` +
				`(${absolute.filter((time) => time.kind === 'instant').length} instant, ` +
				`${absolute.filter((time) => time.kind === 'interval').length} interval, ` +
				`${traces.length - absolute.length} off-axis), ${periods.length} period, ` +
				`${links.length} links → ${batch.entries.length} entries`
		);
	});
});
